-- ===========================================================================
--  Admission, block test and seasonal assessment — `app_rw` grants
--  Migration: AdmissionAndExams
--  Source: docs/modules/admission-and-testing.md §10 (A3), §11
-- ===========================================================================
--
--  DO NOT EDIT THIS FILE.
--  A migration is applied once and is frozen afterwards. A change needs a NEW
--  migration and a new .sql file (the rule of `sales_marketing_guards.sql`).
--
--  WHY THE GRANT LIVES IN THE MIGRATION
--  ------------------------------------
--  Migrations run as `schoollms_owner`; the application connects as `app_rw`,
--  which owns nothing. A forgotten grant does not stop the application from
--  starting — it fails on the FIRST request with SQLSTATE 42501, i.e. in front
--  of a user instead of in development. In this module that first request can
--  be ANONYMOUS: a candidate opening the entrance-test link. So the grant ships
--  with the tables. When the role does not exist yet (a bare database) the
--  block skips with a NOTICE.
--
--  WHY FULL CRUD AND NO `REVOKE` — ON PURPOSE
--  -------------------------------------------
--  None of the twelve tables holds money: no amount, no ledger row, no invoice,
--  no receipt, no cash-shift reference. `docs/SPEC.md` §4.1's immutability rule
--  is about MONEY, and these names are NOT added to the append-only list of
--  `deploy/init-roles.sql` §5. The service deletes and rewrites rows in normal
--  operation: a reset attempt deletes the attempt and its answers, a seasonal
--  mark with neither score nor comment is deleted, a question is edited in place.
--
--  `leads`, `school_meta`, `teachers` — NEW COLUMN / DATA, NO NEW GRANT
--  --------------------------------------------------------------------
--  `GRANT ... ON <table>` covers the whole table, so `leads.admission_status`
--  and `school_meta.admission_show_answers_to_candidate` fall under the existing
--  baseline CRUD of `init-roles.sql` step 4. Nothing to repeat here.
-- ===========================================================================

DO $guards$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
        RAISE NOTICE '[exam_guards] role `app_rw` not found — GRANT skipped. '
                     'Run deploy/init-roles.sql.';
        RETURN;
    END IF;

    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON '
            'public.question_banks, public.questions, public.question_options, '
            'public.exam_types, public.exams, public.exam_sections, '
            'public.exam_participants, public.exam_section_scores, '
            'public.exam_invitations, public.exam_attempts, public.exam_answers, '
            'public.seasonal_marks '
            'TO app_rw';
END
$guards$;
